name: C/C++ CI

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Make
        run: make release

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: markov-video-${{ github.head_ref || github.ref_name }}
          token: ${{ secrets.FINE_GRAINED_SECRET }}
          files: |
            ${{ github.workspace }}/target/release/markov-video${{ matrix.os == 'windows-latest' && '.exe' || '' }}
